'use client';

import React, {
  createContext,
  useContext,
  useEffect,
  useState,
  ReactNode,
} from 'react';
import { getSpeechLangCode } from '@/lib/languages';

// Basic Dictionary for translation
const dictionary: Record<string, Record<string, string>> = {
  English: {
    'expert_title': 'Expert Support Center',
    'expert_subtitle': '24/7 AI and Agronomist Assistance',
    'assistant_greeting': 'Namaste! I am your AI Agronomist. Your wheat crop is 45 days old. How can I help you today?',
    'user_question': 'Leaves are turning yellow in the corner of field.',
    'assistant_reply': 'Yellow leaves can indicate Nitrogen deficiency or Waterlogging. Did it rain heavily recently? Or can you send a photo?',
    'btn_send_photo': 'Send Photo',
    'btn_talk_human': 'Talk to Human Expert',
    'input_placeholder': 'Type or speak (Hindi/English)...',
    'market_title': 'Krishi Bazaar',
    'market_powered': 'POWERED BY RAZORPAY',
    'tab_farmer_sales': 'Farmer Sales',
    'tab_brand_store': 'Brand Store',
    'zero_commission': '⚡ 0% Commission Farmer-to-Farmer Marketplace',
    'seller_label': 'Seller:',
    'btn_negotiate': 'Negotiate',
    'scanner_title': 'Crop AI Engine',
    'scanner_subtitle': 'PlantVillage Dataset Integration',
    'scanner_position': 'Position Plant in Frame',
    'scanner_desc': 'Uses actual native camera logic.',
    'scanner_capture': 'Capture',
    'scanner_btn_scan_another': 'Scan Another Plant',
    'scanner_smart_rx': 'Smart Prescription',
    'scanner_chemical_req': 'Chemical Req.',
    'scanner_water_mix': 'Water Mix',
    'scanner_btn_back': 'Back to Result',
    'home_greeting': 'Hello, Ramesh 👋',
    'home_location': 'Bihar, India',
    'home_loading': 'Loading Smart Insights...',
    'home_scan_title': 'Scan Plant',
    'home_scan_desc': 'Detect disease instantly via AI',
    'home_btn_medicines': 'Medicines',
    'home_btn_buysell': 'Buy/Sell',
    'home_btn_expert': 'Ask Expert',
    'home_btn_dashboard': 'Dashboard',
    'home_health_score': 'CROP HEALTH SCORE',
    'home_weather_alerts': 'Local Geo-Alerts',
    'scanner_medicine': 'Medicine',
    'scanner_pesticide': 'Pesticide',
    'scanner_dosage': 'Dosage',
    'scanner_instructions': 'Instructions',
    'scanner_btn_download_report': 'Download Health Report (PDF)',
    'scanner_confidence': 'Confidence',
    'comm_title': 'Community',
    'comm_tab_reels': 'Reels',
    'comm_tab_discuss': 'Discuss',
    'comm_tab_experts': 'Experts',
    'comm_expert_sos': 'Expert SOS',
    'comm_sos_desc': 'Speak to Doctor for ₹9',
    'comm_call_now': 'Call Now',
    'profile_title': 'Profile',
    'profile_stats_scans': 'Scans',
    'profile_stats_posts': 'Posts',
    'profile_stats_orders': 'Orders',
    'market_rental': 'Rental',
    'market_emi_calc': 'EMI Calculator',
    'market_book_rental': 'Book Rental',
    'nav_home': 'Home',
    'nav_scan': 'Scan',
    'nav_shop': 'Shop',
    'nav_community': 'Community',
    'nav_profile': 'Profile',
    'pd_suite': 'Plant Doctor Intelligence Suite',
    'field_walk': 'for every field walk.',
    '247_hotline': '24/7 Expert Doctor Hotline',
    'shop_title': 'Kisan Bazaar',
    'shop_subtitle': 'Seeds · Meds · Machines · Rentals',
    'shop_sell_btn': 'Sell Item',
    'shop_expert_btn': 'Expert',
    'shop_search_ph': 'Search tractors, seeds, medicines...',
    'shop_cat_all': 'All',
    'shop_cat_medicines': 'Medicines',
    'shop_cat_machines': 'Machines',
    'shop_cat_seeds': 'Seeds',
    'shop_cat_rental': 'Rental',
    'shop_heavy': 'Heavy',
    'shop_tractors_more': 'Tractors & more',
    'shop_badge_verified': 'Verified',
    'shop_badge_premium': 'Premium',
    'shop_badge_eco': 'Eco',
    'shop_badge_official': 'Official',
    'shop_badge_trusted': 'Trusted',
    'shop_badge_top_rated': 'Top Rated',
    'shop_badge_new_seller': 'New Seller',
    'shop_btn_buy': 'Buy',
    'shop_btn_rent': 'Rent',
    'shop_verified_seller': 'Verified Seller',
    'shop_no_products': 'No products found',
    'shop_emi_title': 'Smart EMI Calculator',
    'shop_emi_emi': 'Estimated Monthly EMI',
    'shop_emi_subsidy': '8.5% Govt Subsidy Applied',
    'shop_emi_downpay': 'Downpayment',
    'shop_emi_proceed': 'Proceed to Buy',
    'shop_order_title': 'Place Your Order',
    'shop_rental_title': 'Rental Booking',
    'shop_review_title': 'Confirm Order',
    'shop_review_btn': 'Review Order',
    'shop_confirm_btn': 'Confirm Order',
    'shop_success_msg': 'Order Confirmed!',
    'shop_whatsapp_btn': 'Open WhatsApp Confirmation',
    'shop_continue': 'Continue Shopping',
    'shop_qty': 'Quantity',
    'shop_rental_dur': 'Rental Duration',
    'shop_days': 'days',
    'shop_units': 'units',
    'shop_wa_prompt': 'After placing, we’ll confirm via',
    'shop_wa_via': 'WhatsApp',
    'shop_saved': 'Saved to our system',
    'prof_heading': 'Farmer Profile',
    'prof_farm_identity': 'Farm Identity',
    'prof_farm_type_sub': 'Farm type classification',
    'prof_farm_size': 'Farm Size',
    'prof_voice': 'Voice Assistant',
    'prof_location': 'Location Alerts',
    'prof_enabled': 'Enabled',
    'prof_disabled': 'Disabled',
    'prof_allowed': 'Allowed',
    'prof_skipped': 'Skipped',
    'prof_crop_profile': 'Crop Profile',
    'prof_selected_crops': 'Your Selected Crops',
    'prof_edit': 'Edit',
    'prof_app_language': 'App Language',
    'prof_notif': 'Notifications',
    'prof_notif_sub': 'Daily alerts, scan results',
    'prof_privacy': 'Privacy & Security',
    'prof_privacy_sub': 'Data stays on your device',
    'prof_prefs': 'App Preferences',
    'prof_prefs_sub': 'Camera, voice, themes',
    'prof_restart': 'Restart Onboarding',
    'scanner_pipeline_scan': 'Scan',
    'scanner_pipeline_diagnose': 'Diagnose',
    'scanner_pipeline_prevent': 'Prevent',
    'scanner_pipeline_dosage': 'Dosage',
    'scanner_pipeline_precaution': 'Precaution',
    'scanner_app_title': 'Plant Scanner',
    'scanner_analyzing_leaf': 'Analyzing Leaf',
    'scanner_checking_pathogens': 'Checking against 38,000+ pathogens',
    'scanner_step_0': 'Extracting visual features',
    'scanner_step_1': 'Pattern matching diseases',
    'scanner_step_2': 'Geo-locating outbreak data',
    'scanner_ai_processing': 'AI Processing',
    'scanner_high_severity': 'High Severity',
    'scanner_medium_severity': 'Medium Severity',
    'scanner_early_detection': 'Early Detection',
    'scanner_match': 'Match',
    'scanner_based_on_visual': 'Based on visual symptoms & local outbreak data',
    'scanner_ai_action': 'AI Action',
    'scanner_human_review': 'Human Review Recommended',
    'scanner_spray_decision': 'Spray decision lene se pehle expert se confirm karein.',
    'scanner_treatment_plan': 'Treatment Plan',
    'scanner_btn_talk': 'Talk to Agronomist Now',
    'scanner_btn_compute': 'Compute Exact Dosage',
    'scanner_btn_shop': 'Shop Products',
    'scanner_btn_new': 'New Scan',
    'scanner_live_badge': 'Live',
    'scanner_center_leaf': 'Center the affected leaf',
    'scanner_camera_unavailable': 'Camera Unavailable',
    'scanner_try_again': 'Try Again',
    'scanner_upload_gallery': 'Or upload from gallery · Supports JPG, PNG, HEIC' ,
    'intel_smart_irrigation': 'Smart Irrigation',
    'intel_live_forecast': 'Live Forecast',
    'intel_irrigation_msg': 'Irrigation plan based on local weather and field soil.',
    'intel_suggested_interval': 'Suggested interval',
    'intel_soil_profile': 'Soil profile',
    'intel_roi_profitability': 'ROI & Profitability',
    'intel_investment': 'Investment',
    'intel_expected_income': 'Expected Income',
    'intel_net_profit': 'Net Profit',
    'intel_yield': 'Yield',
    'intel_mandi_signal': 'Mandi signal',
    'intel_mandi_live': 'Mandi Live',
    'intel_price_falling': 'Prices are falling',
    'intel_price_rising': 'Prices are rising',
    'intel_stable': 'Stable',
    'intel_per_quintal': 'per quintal',
    'intel_share_roi': 'Share Expected ROI',
    'pd_suite': 'Plant Doctor Intelligence Suite',
    'scanner_smart_rx': 'Smart AI Advice',
    '247_hotline': '24/7 Expert Doctor Hotline'
  },
  'हिंदी': {
    'expert_title': 'विशेषज्ञ सहायता केंद्र',
    'expert_subtitle': '24/7 AI और कृषि विशेषज्ञ सहायता',
    'assistant_greeting': 'नमस्ते! मैं आपका AI कृषि विशेषज्ञ हूँ। आपकी गेहूं की फसल 45 दिन की है। आज मैं आपकी कैसे मदद कर सकता हूँ?',
    'user_question': 'खेत के कोने में पत्तियां पीली पड़ रही हैं।',
    'assistant_reply': 'पीली पत्तियां नाइट्रोजन की कमी या जलभराव का संकेत हो सकती हैं। क्या हाल ही में भारी बारिश हुई थी? या क्या आप फोटो भेज सकते हैं?',
    'btn_send_photo': 'फोटो भेजें',
    'btn_talk_human': 'मानव विशेषज्ञ से बात करें',
    'input_placeholder': 'टाइप करें या बोलें...',
    'market_title': 'कृषि बाज़ार',
    'market_powered': 'रेज़रपे द्वारा संचालित',
    'tab_farmer_sales': 'किसान बिक्री',
    'tab_brand_store': 'ब्रांड स्टोर',
    'zero_commission': '⚡ 0% कमीशन किसान-से-किसान बाज़ार',
    'seller_label': 'विक्रेता:',
    'btn_negotiate': 'मोलभाव करें',
    'scanner_title': 'फसल AI इंजन',
    'scanner_subtitle': 'प्लांटविलेज डेटासेट एकीकरण',
    'scanner_position': 'पौधे को फ्रेम में रखें',
    'scanner_desc': 'वास्तविक कैमरा लॉजिक का उपयोग करता है।',
    'scanner_capture': 'तस्वीर खींचें',
    'scanner_btn_scan_another': 'दूसरा पौधा स्कैन करें',
    'scanner_smart_rx': 'स्मार्ट पर्ची',
    'scanner_chemical_req': 'दवा की आवश्यकता',
    'scanner_water_mix': 'पानी की मात्रा',
    'scanner_btn_back': 'परिणाम पर वापस जाएं',
    'home_greeting': 'नमस्ते, रमेश 👋',
    'home_location': 'बिहार, भारत',
    'home_loading': 'स्मार्ट जानकारी लोड हो रही है...',
    'home_scan_title': 'पौधा स्कैन करें',
    'home_scan_desc': 'AI द्वारा तुरंत बीमारी का पता लगाएं',
    'home_btn_medicines': 'दवाइयां',
    'home_btn_buysell': 'खरीदें/बेचें',
    'home_btn_expert': 'विशेषज्ञ से पूछें',
    'home_btn_dashboard': 'डैशबोर्ड',
    'home_health_score': 'फसल स्वास्थ्य स्कोर',
    'home_weather_alerts': 'स्थानीय अलर्ट',
    'comm_title': 'समुदाय',
    'comm_tab_reels': 'रील्स',
    'comm_tab_discuss': 'चर्चा',
    'comm_tab_experts': 'विशेषज्ञ',
    'comm_expert_sos': 'विशेषज्ञ SOS',
    'comm_sos_desc': '₹9 में डॉक्टर से बात करें',
    'comm_call_now': 'अभी कॉल करें',
    'profile_title': 'प्रोफ़ाइल',
    'profile_stats_scans': 'स्कैन',
    'profile_stats_posts': 'पोस्ट',
    'profile_stats_orders': 'ऑर्डर',
    'market_rental': 'किराया',
    'market_emi_calc': 'EMI कैलकुलेटर',
    'market_book_rental': 'किराया बुक करें',
    'nav_home': 'होम',
    'nav_scan': 'स्कैन',
    'nav_shop': 'दुकान',
    'nav_community': 'समुदाय',
    'nav_profile': 'प्रोफ़ाइल',
    'pd_suite': 'प्लांट डॉक्टर इंटेलिजेंस सूट',
    'field_walk': 'हर खेत के चक्कर के लिए।',
    '247_hotline': '24/7 विशेषज्ञ डॉक्टर हॉटलाइन',
    'shop_title': 'किसान बाज़ार',
    'shop_subtitle': 'बीज · दवा · मशीनें · किराया',
    'shop_sell_btn': 'बेचें',
    'shop_expert_btn': 'विशेषज्ञ',
    'shop_search_ph': 'ट्रैक्टर, बीज, दवा...',
    'shop_cat_all': 'सभी',
    'shop_cat_medicines': 'दवाइयाँ',
    'shop_cat_machines': 'मशीनें',
    'shop_cat_seeds': 'बीज',
    'shop_cat_rental': 'किराया',
    'shop_heavy': 'भारी',
    'shop_tractors_more': 'ट्रैक्टर और अधिक',
    'shop_badge_verified': 'प्रमाणित',
    'shop_badge_premium': 'प्रीमियम',
    'shop_badge_eco': 'इको',
    'shop_badge_official': 'आधिकारिक',
    'shop_badge_trusted': 'विश्वसनीय',
    'shop_badge_top_rated': 'शीर्ष रेटेड',
    'shop_badge_new_seller': 'नया विक्रेता',
    'shop_btn_buy': 'खरीदें',
    'shop_btn_rent': 'किराए पर',
    'shop_verified_seller': 'प्रमाणित विक्रेता',
    'shop_no_products': 'कोई उत्पाद नहीं मिला',
    'shop_emi_title': 'स्मार्ट EMI कैलकुलेटर',
    'shop_emi_emi': 'अनुमानित मासिक EMI',
    'shop_emi_subsidy': '8.5% सरकारी सब्सिडी लागू',
    'shop_emi_downpay': 'डाउनपेमेंट',
    'shop_emi_proceed': 'खरीदने जाएं',
    'shop_order_title': 'ऑर्डर दें',
    'shop_rental_title': 'किराया बुकिंग',
    'shop_review_title': 'ऑर्डर कनफर्म करें',
    'shop_review_btn': 'ऑर्डर देखें',
    'shop_confirm_btn': 'ऑर्डर कनफर्म करें',
    'shop_success_msg': 'ऑर्डर हो गया!',
    'shop_whatsapp_btn': 'WhatsApp पर पुष्टि देखें',
    'shop_continue': 'खरीदारी जारी रखें',
    'shop_qty': 'मात्रा',
    'shop_rental_dur': 'किराया अवधि',
    'shop_days': 'दिन',
    'shop_units': 'यूनिट',
    'shop_wa_prompt': 'ऑर्डर के बाद पुष्टि',
    'shop_wa_via': 'WhatsApp',
    'shop_saved': 'हमारे सिस्टम में सेव हो गया',
    'prof_heading': 'किसान प्रोफ़ाइल',
    'prof_farm_identity': 'फार्म पहचान',
    'prof_farm_type_sub': 'फार्म प्रकार',
    'prof_farm_size': 'खेत का आकार',
    'prof_voice': 'वॉयस असिस्टेंट',
    'prof_location': 'लोकेशन अलर्ट',
    'prof_enabled': 'चालू',
    'prof_disabled': 'बंद',
    'prof_allowed': 'अनुमत',
    'prof_skipped': 'छोड़ा',
    'prof_crop_profile': 'फसल प्रोफ़ाइल',
    'prof_selected_crops': 'आपकी चुनी हुई फसलें',
    'prof_edit': 'बदलें',
    'prof_app_language': 'ऐप भाषा',
    'prof_notif': 'सूचनाएं',
    'prof_notif_sub': 'रोज़ाना अलर्ट, स्कैन रिपोर्ट',
    'prof_privacy': 'गोपनीयता और सुरक्षा',
    'prof_privacy_sub': 'डेटा आपके डिवाइस पर रहता है',
    'prof_prefs': 'ऐप सेटिंग्स',
    'prof_prefs_sub': 'कैमरा, आवाज़, थीम',
    'prof_restart': 'ऑनबोर्डिंग दोबारा शुरू करें',
    'scanner_pipeline_scan': 'स्कैन',
    'scanner_pipeline_diagnose': 'निदान',
    'scanner_pipeline_prevent': 'बचाव',
    'scanner_pipeline_dosage': 'मात्रा',
    'scanner_pipeline_precaution': 'सावधानी',
    'scanner_app_title': 'पौधा स्कैनर',
    'scanner_analyzing_leaf': 'पत्ती की जाँच हो रही है',
    'scanner_checking_pathogens': '38,000+ बीमारियों का मिलान',
    'scanner_step_0': 'दिखने वाले लक्षण निकाले जा रहे हैं',
    'scanner_step_1': 'बीमारी का पैटर्न मिला रहे हैं',
    'scanner_step_2': 'आसपास के इलाकों का डेटा चेक कर रहे हैं',
    'scanner_ai_processing': 'AI प्रोसेसिंग',
    'scanner_high_severity': 'गंभीर स्थिति',
    'scanner_medium_severity': 'मध्यम स्थिति',
    'scanner_early_detection': 'शुरुआती पहचान',
    'scanner_match': 'मिलान',
    'scanner_based_on_visual': 'लक्षणों और आस-पास की बीमारियों के आधार पर',
    'scanner_ai_action': 'AI की सलाह',
    'scanner_human_review': 'विशेषज्ञ की सलाह',
    'scanner_spray_decision': 'स्प्रे का निर्णय लेने से पहले विशेषज्ञ से बात करें।',
    'scanner_treatment_plan': 'उपचार योजना',
    'scanner_btn_talk': 'अभी कृषि विशेषज्ञ से बात करें',
    'scanner_btn_compute': 'दवा की सही मात्रा जानें',
    'scanner_btn_shop': 'दवाइयां खरीदें',
    'scanner_btn_new': 'नया स्कैन करें',
    'scanner_live_badge': 'लाइव',
    'scanner_center_leaf': 'बीमार पत्ती को बीच में रखें',
    'scanner_camera_unavailable': 'कैमरा उपलब्ध नहीं है',
    'scanner_try_again': 'फिर से कोशिश करें',
    'scanner_upload_gallery': 'या गैलरी से फोटो अपलोड करें',
    'intel_smart_irrigation': 'स्मार्ट सिंचाई',
    'intel_live_forecast': 'लाइव पूर्वानुमान',
    'intel_irrigation_msg': 'स्थानीय मौसम और मिट्टी के आधार पर सिंचाई योजना।',
    'intel_suggested_interval': 'सुझाया गया अंतराल',
    'intel_soil_profile': 'मिट्टी का प्रकार',
    'intel_roi_profitability': 'ROI और लाभ',
    'intel_investment': 'निवेश',
    'intel_expected_income': 'अनुमानित आय',
    'intel_net_profit': 'शुद्ध लाभ',
    'intel_yield': 'उपज',
    'intel_mandi_signal': 'मंडी संकेत',
    'intel_mandi_live': 'मंडी भाव • लाइव',
    'intel_price_falling': 'कीमत गिर रही है',
    'intel_price_rising': 'कीमत बढ़ रही है',
    'intel_stable': 'स्थिर',
    'intel_per_quintal': 'प्रति क्विंटल',
    'intel_share_roi': 'Expected ROI शेयर करें',
    'pd_suite': 'प्लांट डॉक्टर इंटेलिजेंस सूट',
    'scanner_smart_rx': 'स्मार्ट AI सलाह',
    '247_hotline': '24/7 विशेषज्ञ डॉक्टर हॉटलाइन'
  },
  'भोजपुरी': {
    'expert_title': 'विशेषज्ञ मदद केंद्र',
    'expert_subtitle': '24/7 AI आउर कृषि विशेषज्ञ सहायता',
    'assistant_greeting': 'प्रणाम! हम राउर AI कृषि विशेषज्ञ बानी। राउर गेहूं के फसल 45 दिन के बा। आज हम राउर कइसे मदद करीं?',
    'user_question': 'खेत के कोना में पतई पियर हो रहल बा।',
    'assistant_reply': 'पियर पतई नाइट्रोजन के कमी या पानी लागे के संकेत हो सकेला। का हाल में भारी बरखा भइल रहे? भा रउआ फोटो भेज सकत बानी?',
    'btn_send_photo': 'फोटो भेजीं',
    'btn_talk_human': 'आदमी विशेषज्ञ से बतियाईं',
    'input_placeholder': 'टाइप करीं या बोलीं...',
    'market_title': 'कृषि बजार',
    'market_powered': 'रेज़रपे से चलल',
    'tab_farmer_sales': 'किसान के बिक्री',
    'tab_brand_store': 'ब्रांड दोकान',
    'zero_commission': '⚡ 0% कमीशन किसान-से-किसान बजार',
    'seller_label': 'बेचे वाला:',
    'btn_negotiate': 'मोलभाव करीं',
    'scanner_title': 'फसल AI इंजन',
    'scanner_subtitle': 'प्लान्टविलेज डेटासेट जुड़ाव',
    'scanner_position': 'फसल के फ्रेम में रखीं',
    'scanner_desc': 'असली कैमरा के इस्तेमाल करत बा।',
    'scanner_capture': 'फोटो खींचीं',
    'scanner_btn_scan_another': 'दोसर फसल स्कैन करीं',
    'scanner_smart_rx': 'स्मार्ट राय',
    'scanner_chemical_req': 'दावा के जरूरत',
    'scanner_water_mix': 'पानी के मात्रा',
    'scanner_btn_back': 'रिजल्ट प वापस जाईं',
    'home_greeting': 'प्रणाम, रमेश 👋',
    'home_location': 'बिहार, भारत',
    'home_loading': 'स्मार्ट जानकारी लोड होखे त बा...',
    'home_scan_title': 'फसल स्कैन करीं',
    'home_scan_desc': 'AI से तुरंत बीमारी खोजीं',
    'home_btn_medicines': 'दावा-बीरो',
    'home_btn_buysell': 'किनल/बेचल',
    'home_btn_expert': 'विशेषज्ञ से पूछीं',
    'home_btn_dashboard': 'खाता-बही',
    'home_health_score': 'फसल के सेहत',
    'home_weather_alerts': 'गाँव के अलर्ट',
    'scanner_medicine': 'दावा',
    'scanner_pesticide': 'कीड़ा मार दावा',
    'scanner_dosage': 'कितना डालीं',
    'scanner_instructions': 'तरीका',
    'scanner_btn_download_report': 'रिपोर्ट डाउनलोड करीं (PDF)',
    'scanner_confidence': 'भरोसा',
    'nav_home': 'होम',
    'nav_scan': 'स्कैन',
    'nav_shop': 'दुकान',
    'nav_community': 'समाज',
    'nav_profile': 'प्रोफाइल',
    'pd_suite': 'प्लांट डॉक्टर सूट',
    'field_walk': 'हर खेत के चक्कर खातिर।',
    'shop_title': 'किसान बजार',
    'shop_subtitle': 'बीज · दवा · मशीन · किराया',
    'shop_sell_btn': 'बेची',
    'shop_expert_btn': 'विशेषज्ञ',
    'shop_search_ph': 'ट्रैक्टर, बीज, दवा ढूंढीं...',
    'shop_cat_all': 'सब',
    'shop_cat_medicines': 'दवाइयाँ',
    'shop_cat_machines': 'मशीन',
    'shop_cat_seeds': 'बीज',
    'shop_cat_rental': 'किराया',
    'shop_heavy': 'भारी',
    'shop_tractors_more': 'ट्रैक्टर आउर बाकी',
    'shop_badge_verified': 'प्रमाणित',
    'shop_badge_premium': 'प्रीमियम',
    'shop_badge_eco': 'इको',
    'shop_badge_official': 'आधिकारिक',
    'shop_badge_trusted': 'भरोसेमंद',
    'shop_badge_top_rated': 'टॉप रेटेड',
    'shop_badge_new_seller': 'नया दोकानदार',
    'shop_btn_buy': 'खरीदीं',
    'shop_btn_rent': 'किराया पर',
    'shop_verified_seller': 'प्रमाणित दोकानदार',
    'shop_no_products': 'कउनो उत्पाद ना मिलल',
    'shop_emi_title': 'स्मार्ट EMI कैलकुलेटर',
    'shop_emi_emi': 'अनुमानित महीना EMI',
    'shop_emi_subsidy': '8.5% सरकारी सब्सिडी लागू',
    'shop_emi_downpay': 'डाउनपेमेंट',
    'shop_emi_proceed': 'खरीदे जाईं',
    'shop_order_title': 'ऑर्डर दीं',
    'shop_rental_title': 'किराया बुकिंग',
    'shop_review_title': 'ऑर्डर पक्का करीं',
    'shop_review_btn': 'ऑर्डर देखीं',
    'shop_confirm_btn': 'ऑर्डर कनफर्म करीं',
    'shop_success_msg': 'ऑर्डर हो गइल!',
    'shop_whatsapp_btn': 'WhatsApp पर पुष्टि देखीं',
    'shop_continue': 'खरीदारी जारी राखीं',
    'shop_qty': 'मात्रा',
    'shop_rental_dur': 'किराया अवधि',
    'shop_days': 'दिन',
    'shop_units': 'यूनिट',
    'shop_wa_prompt': 'ऑर्डर के बाद पुष्टि',
    'shop_wa_via': 'WhatsApp',
    'shop_saved': 'हमार सिस्टम में सेव हो गइल',
    'prof_heading': 'किसान प्रोफाइल',
    'prof_farm_identity': 'खेत पहचान',
    'prof_farm_type_sub': 'खेत के किसिम',
    'prof_farm_size': 'खेत के नाप',
    'prof_voice': 'आवाज़ असिस्टेंट',
    'prof_location': 'लोकेशन अलर्ट',
    'prof_enabled': 'चालू बा',
    'prof_disabled': 'बंद बा',
    'prof_allowed': 'मंजूर बा',
    'prof_skipped': 'छोड़ल बा',
    'prof_crop_profile': 'फसल प्रोफाइल',
    'prof_selected_crops': 'रउआ के फसल',
    'prof_edit': 'बदली',
    'prof_app_language': 'ऐप भाषा',
    'prof_notif': 'सूचना',
    'prof_notif_sub': 'रोज के अलर्ट, स्कैन रिपोर्ट',
    'prof_privacy': 'गोपनीयता आउर सुरक्षा',
    'prof_privacy_sub': 'डेटा रउआ के डिवाइस पर रही',
    'prof_prefs': 'ऐप सेटिंग',
    'prof_prefs_sub': 'कैमरा, आवाज़, थीम',
    'prof_restart': 'ऑनबोर्डिंग फिर से शुरू करीं',
    'scanner_pipeline_scan': 'Scan',
    'scanner_pipeline_diagnose': 'Diagnose',
    'scanner_pipeline_prevent': 'Prevent',
    'scanner_pipeline_dosage': 'Dosage',
    'scanner_pipeline_precaution': 'Precaution',
    'scanner_app_title': 'Plant Scanner',
    'scanner_analyzing_leaf': 'Analyzing Leaf',
    'scanner_checking_pathogens': 'Checking against 38,000+ pathogens',
    'scanner_step_0': 'Extracting visual features',
    'scanner_step_1': 'Pattern matching diseases',
    'scanner_step_2': 'Geo-locating outbreak data',
    'scanner_ai_processing': 'AI Processing',
    'scanner_high_severity': 'High Severity',
    'scanner_medium_severity': 'Medium Severity',
    'scanner_early_detection': 'Early Detection',
    'scanner_match': 'Match',
    'scanner_based_on_visual': 'Based on visual symptoms & local outbreak data',
    'scanner_ai_action': 'AI Action',
    'scanner_human_review': 'Human Review Recommended',
    'scanner_spray_decision': 'Spray decision lene se pehle expert se confirm karein.',
    'scanner_treatment_plan': 'Treatment Plan',
    'scanner_btn_talk': 'Talk to Agronomist Now',
    'scanner_btn_compute': 'Compute Exact Dosage',
    'scanner_btn_shop': 'Shop Products',
    'scanner_btn_new': 'New Scan',
    'scanner_live_badge': 'Live',
    'scanner_center_leaf': 'Center the affected leaf',
    'scanner_camera_unavailable': 'Camera Unavailable',
    'scanner_try_again': 'Try Again',
    'scanner_upload_gallery': 'Or upload from gallery · Supports JPG, PNG, HEIC'
  },
  'ਪੰਜਾਬੀ': {
    'expert_title': 'ਮਾਹਰ ਸਹਾਇਤਾ ਕੇਂਦਰ',
    'expert_subtitle': '24/7 AI ਅਤੇ ਖੇਤੀਬਾੜੀ ਮਾਹਰ ਸਹਾਇਤਾ',
    'assistant_greeting': 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਤੁਹਾਡਾ AI ਖੇਤੀਬਾੜੀ ਮਾਹਰ ਹਾਂ। ਤੁਹਾਡੀ ਕਣਕ ਦੀ ਫਸਲ 45 ਦਿਨਾਂ ਦੀ ਹੈ। ਮੈਂ ਅੱਜ ਤੁਹਾਡੀ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ?',
    'user_question': 'ਖੇਤ ਦੇ ਕੋਨੇ ਵਿੱਚ ਪੱਤੇ ਪੀਲੇ ਹੋ ਰਹੇ ਹਨ।',
    'assistant_reply': 'ਪੀਲੇ ਪੱਤੇ ਨਾਈਟ੍ਰੋਜਨ ਦੀ ਕਮੀ ਜਾਂ ਪਾਣੀ ਭਰਨ ਦਾ ਸੰਕੇਤ ਹੋ ਸਕਦੇ ਹਨ। ਕੀ ਹਾਲ ਹੀ ਵਿੱਚ ਭਾਰੀ ਮੀਂਹ ਪਿਆ ਸੀ? ਜਾਂ ਕੀ ਤੁਸੀਂ ਇੱਕ ਫੋਟੋ ਭੇਜ ਸਕਦੇ ਹੋ?',
    'btn_send_photo': 'ਫੋਟੋ ਭੇਜੋ',
    'btn_talk_human': 'ਮਨੁੱਖੀ ਮਾਹਰ ਨਾਲ ਗੱਲ ਕਰੋ',
    'input_placeholder': 'ਟਾਈਪ ਕਰੋ ਜਾਂ ਬੋਲੋ...',
    'market_title': 'ਕ੍ਰਿਸ਼ੀ ਬਾਜ਼ਾਰ',
    'market_powered': 'ਰੇਜ਼ਰਪੇ ਦੁਆਰਾ ਸੰਚਾਲਿਤ',
    'tab_farmer_sales': 'ਕਿਸਾਨ ਵਿਕਰੀ',
    'tab_brand_store': 'ਬ੍ਰਾਂਡ ਸਟੋਰ',
    'zero_commission': '⚡ 0% ਕਮਿਸ਼ਨ ਕਿਸਾਨ-ਤੋਂ-ਕਿਸਾਨ ਬਾਜ਼ਾਰ',
    'seller_label': 'ਵਿਕਰੇਤਾ:',
    'btn_negotiate': 'ਗੱਲਬਾਤ ਕਰੋ',
    'scanner_title': 'ਫਸਲ AI ਇੰਜਨ',
    'scanner_subtitle': 'ਪਲਾਂਟਵਿਲੇਜ ਡੇਟਾਸੈਟ ਏਕੀਕਰਣ',
    'scanner_position': 'ਪੌਦੇ ਨੂੰ ਫਰੇਮ ਵਿੱਚ ਰੱਖੋ',
    'scanner_desc': 'ਅਸਲ ਕੈਮਰਾ ਲਾਜਿਕ ਦੀ ਵਰਤੋਂ ਕਰਦਾ ਹੈ।',
    'scanner_capture': 'ਫੋਟੋ ਖਿੱਚੋ',
    'scanner_btn_scan_another': 'ਇੱਕ ਹੋਰ ਪੌਦਾ ਸਕੈਨ ਕਰੋ',
    'scanner_smart_rx': 'ਸਮਾਰਟ ਪਰਚੀ',
    'scanner_chemical_req': 'ਦਵਾਈ ਦੀ ਲੋੜ',
    'scanner_water_mix': 'ਪਾਣੀ ਦਾ ਮਿਸ਼ਰਣ',
    'scanner_btn_back': 'ਨਤੀਜੇ ਤੇ ਵਾਪਸ ਜਾਓ',
    'home_greeting': 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ, ਰਮੇਸ਼ 👋',
    'home_location': 'ਪੰਜਾਬ, ਭਾਰਤ',
    'home_loading': 'ਸਮਾਰਟ ਜਾਣਕਾਰੀ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...',
    'home_scan_title': 'ਪੌਦਾ ਸਕੈਨ ਕਰੋ',
    'home_scan_desc': 'AI ਦੁਆਰਾ ਤੁਰੰਤ ਬਿਮਾਰੀ ਦਾ ਪਤਾ ਲਗਾਓ',
    'home_btn_medicines': 'ਦਵਾਈਆਂ',
    'home_btn_buysell': 'ਖਰੀਦੋ/ਵੇਚੋ',
    'home_btn_expert': 'ਮਾਹਰ ਨੂੰ ਪੁੱਛੋ',
    'home_btn_dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'home_health_score': 'ਫਸਲ ਸਿਹਤ ਸਕੋਰ',
    'home_weather_alerts': 'ਸਥਾਨਕ ਅਲਰਟ',
    'scanner_medicine': 'ਦਵਾਈ',
    'scanner_pesticide': 'ਕੀੜੇਮਾਰ ਦਵਾਈ',
    'scanner_dosage': 'ਖੁਰਾਕ (ਡੋਜ਼)',
    'scanner_instructions': 'ਹਦਾਇਤਾਂ',
    'scanner_btn_download_report': 'ਸਿਹਤ ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ (PDF)',
    'scanner_confidence': 'ਭਰੋਸਾ',
    'nav_home': 'ਹੋਮ',
    'nav_scan': 'ਸਕੈਨ',
    'nav_shop': 'ਦੁਕਾਨ',
    'nav_community': 'ਭਾਈਚਾਰਾ',
    'nav_profile': 'ਪ੍ਰੋਫਾਈਲ',
    'pd_suite': 'ਪਲਾਂਟ ਡਾਕਟਰ ਸੂਟ',
    'field_walk': 'ਹਰ ਖੇਤ ਦੇ ਦੌਰੇ ਲਈ।',
    'shop_title': 'ਕਿਸਾਨ ਬਾਜ਼ਾਰ',
    'shop_subtitle': 'ਬੀਜ · ਦਵਾਈ · ਮਸ਼ੀਨਾਂ · ਕਿਰਾਇਆ',
    'shop_sell_btn': 'ਵੇਚੋ',
    'shop_expert_btn': 'ਮਾਹਰ',
    'shop_search_ph': 'ਟਰੈਕਟਰ, ਬੀਜ, ਦਵਾਈ ਲੱਭੋ...',
    'shop_cat_all': 'ਸਭ',
    'shop_cat_medicines': 'ਦਵਾਈਆਂ',
    'shop_cat_machines': 'ਮਸ਼ੀਨਾਂ',
    'shop_cat_seeds': 'ਬੀਜ',
    'shop_cat_rental': 'ਕਿਰਾਇਆ',
    'shop_heavy': 'ਭਾਰੀ',
    'shop_tractors_more': 'ਟਰੈਕਟਰ ਤੇ ਹੋਰ',
    'shop_badge_verified': 'ਪ੍ਰਮਾਣਿਤ',
    'shop_badge_premium': 'ਪ੍ਰੀਮੀਅਮ',
    'shop_badge_eco': 'ਇਕੋ',
    'shop_badge_official': 'ਅਧਿਕਾਰਿਕ',
    'shop_badge_trusted': 'ਭਰੋਸੇਯੋਗ',
    'shop_badge_top_rated': 'ਚੋਟੀ ਰੇਟਡ',
    'shop_badge_new_seller': 'ਨਵਾਂ ਵਿਕਰੇਤਾ',
    'shop_btn_buy': 'ਖਰੀਦੋ',
    'shop_btn_rent': 'ਕਿਰਾਏ ਤੇ',
    'shop_verified_seller': 'ਪ੍ਰਮਾਣਿਤ ਵਿਕਰੇਤਾ',
    'shop_no_products': 'ਕੋਈ ਉਤਪਾਦ ਨਹੀਂ ਮਿਲਿਆ',
    'shop_emi_title': 'ਸਮਾਰਟ EMI ਕੈਲਕੁਲੇਟਰ',
    'shop_emi_emi': 'ਅਨੁਮਾਨਿਤ ਮਾਸਿਕ EMI',
    'shop_emi_subsidy': '8.5% ਸਰਕਾਰੀ ਸਬਸਿਡੀ ਲਾਗੂ',
    'shop_emi_downpay': 'ਡਾਊਨਪੇਮੈਂਟ',
    'shop_emi_proceed': 'ਖਰੀਦਣ ਜਾਓ',
    'shop_order_title': 'ਆਰਡਰ ਦਿਓ',
    'shop_rental_title': 'ਕਿਰਾਇਆ ਬੁਕਿੰਗ',
    'shop_review_title': 'ਆਰਡਰ ਪੱਕਾ ਕਰੋ',
    'shop_review_btn': 'ਆਰਡਰ ਦੇਖੋ',
    'shop_confirm_btn': 'ਆਰਡਰ ਕਨਫਰਮ ਕਰੋ',
    'shop_success_msg': 'ਆਰਡਰ ਹੋ ਗਿਆ!',
    'shop_whatsapp_btn': 'WhatsApp ਤੇ ਪੁਸ਼ਟੀ ਦੇਖੋ',
    'shop_continue': 'ਖਰੀਦਦਾਰੀ ਜਾਰੀ ਰੱਖੋ',
    'shop_qty': 'ਮਾਤਰਾ',
    'shop_rental_dur': 'ਕਿਰਾਇਆ ਅਵਧੀ',
    'shop_days': 'ਦਿਨ',
    'shop_units': 'ਯੂਨਿਟ',
    'shop_wa_prompt': 'ਆਰਡਰ ਤੋਂ ਬਾਅਦ ਪੁਸ਼ਟੀ',
    'shop_wa_via': 'WhatsApp',
    'shop_saved': 'ਸਾਡੇ ਸਿਸਟਮ ਵਿੱਚ ਸੇਵ ਹੋ ਗਿਆ',
    'prof_heading': 'ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ',
    'prof_farm_identity': 'ਖੇਤ ਪਛਾਣ',
    'prof_farm_type_sub': 'ਖੇਤ ਦੀ ਕਿਸਮ',
    'prof_farm_size': 'ਖੇਤ ਦਾ ਆਕਾਰ',
    'prof_voice': 'ਵੌਇਸ ਅਸਿਸਟੈਂਟ',
    'prof_location': 'ਲੋਕੇਸ਼ਨ ਅਲਰਟ',
    'prof_enabled': 'ਚਾਲੂ',
    'prof_disabled': 'ਬੰਦ',
    'prof_allowed': 'ਮਨਜ਼ੂਰ',
    'prof_skipped': 'ਛੱਡਿਆ',
    'prof_crop_profile': 'ਫਸਲ ਪ੍ਰੋਫਾਈਲ',
    'prof_selected_crops': 'ਤੁਹਾਡੀਆਂ ਫਸਲਾਂ',
    'prof_edit': 'ਬਦਲੋ',
    'prof_app_language': 'ਐਪ ਭਾਸ਼ਾ',
    'prof_notif': 'ਸੂਚਨਾਵਾਂ',
    'prof_notif_sub': 'ਰੋਜ਼ਾਨਾ ਅਲਰਟ, ਸਕੈਨ ਰਿਪੋਰਟ',
    'prof_privacy': 'ਗੁਪਤਤਾ ਅਤੇ ਸੁਰੱਖਿਆ',
    'prof_privacy_sub': 'ਡੇਟਾ ਤੁਹਾਡੇ ਡਿਵਾਈਸ ਤੇ ਰਹਿੰਦਾ ਹੈ',
    'prof_prefs': 'ਐਪ ਸੈਟਿੰਗਾਂ',
    'prof_prefs_sub': 'ਕੈਮਰਾ, ਅਵਾਜ਼, ਥੀਮ',
    'prof_restart': 'ਓਨਬੋਰਡਿੰਗ ਦੁਬਾਰਾ ਸ਼ੁਰੂ ਕਰੋ',
    'scanner_pipeline_scan': 'ਸਕੈਨ',
    'scanner_pipeline_diagnose': 'ਜਾਂਚ',
    'scanner_pipeline_prevent': 'ਬਚਾਅ',
    'scanner_pipeline_dosage': 'ਖੁਰਾਕ',
    'scanner_pipeline_precaution': 'ਸਾਵਧਾਨੀ',
    'scanner_app_title': 'ਪੌਦਾ ਸਕੈਨਰ',
    'scanner_analyzing_leaf': 'ਪੱਤੇ ਦੀ ਜਾਂਚ ਹੋ ਰਹੀ ਹੈ',
    'scanner_checking_pathogens': '38,000+ ਬਿਮਾਰੀਆਂ ਨਾਲ ਮੇਲਾਣ',
    'scanner_step_0': 'ਲੱਛਣਾਂ ਦੀ ਪਛਾਣ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ',
    'scanner_step_1': 'ਬਿਮਾਰੀ ਦਾ ਪੈਟਰਨ ਮਿਲਾ ਰਹੇ ਹਾਂ',
    'scanner_step_2': 'ਆਸ-ਪਾਸ ਦੇ ਇਲਾਕਿਆਂ ਦਾ ਡੇਟਾ ਚੈੱਕ ਕਰ ਰਹੇ ਹਾਂ',
    'scanner_ai_processing': 'AI ਪ੍ਰੋਸੈਸਿੰਗ',
    'scanner_high_severity': 'ਗੰਭੀਰ ਸਥਿਤੀ',
    'scanner_medium_severity': 'ਔਸਤ ਸਥਿਤੀ',
    'scanner_early_detection': 'ਸ਼ੁਰੂਆਤੀ ਪਛਾਣ',
    'scanner_match': 'ਮੇਲਾਣ',
    'scanner_based_on_visual': 'ਲੱਛਣਾਂ ਅਤੇ ਆਲੇ-ਦੁਆਲੇ ਦੀਆਂ ਬਿਮਾਰੀਆਂ ਦੇ ਅਧਾਰ ਤੇ',
    'scanner_ai_action': 'AI ਦੀ ਸਲਾਹ',
    'scanner_human_review': 'ਮਾਹਰ ਦੀ ਸਲਾਹ',
    'scanner_spray_decision': 'ਸਪ੍ਰੇ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਮਾਹਰ ਨਾਲ ਗੱਲ ਕਰੋ।',
    'scanner_treatment_plan': 'ਇਲਾਜ ਯੋਜਨਾ',
    'scanner_btn_talk': 'ਹੁਣ ਖੇਤੀਬਾੜੀ ਮਾਹਰ ਨਾਲ ਗੱਲ ਕਰੋ',
    'scanner_btn_compute': 'ਦਵਾਈ ਦੀ ਸਹੀ ਮਾਤਰਾ ਜਾਣੋ',
    'scanner_btn_shop': 'ਦਵਾਈਆਂ ਖਰੀਦੋ',
    'scanner_btn_new': 'ਨਵਾਂ ਸਕੈਨ ਕਰੋ',
    'scanner_live_badge': 'ਲਾਈਵ',
    'scanner_center_leaf': 'ਬਿਮਾਰ ਪੱਤੇ ਨੂੰ ਵਿਚਕਾਰ ਰੱਖੋ',
    'scanner_camera_unavailable': 'ਕੈਮਰਾ ਉਪਲਬਧ ਨਹੀਂ ਹੈ',
    'scanner_try_again': 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
    'scanner_upload_gallery': 'ਜਾਂ ਗੈਲਰੀ ਤੋਂ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ'
  },
  'मैथिली': {
    'expert_title': 'विशेषज्ञ सहायता केंद्र',
    'expert_subtitle': '24/7 AI आ कृषि विशेषज्ञ सहायता',
    'assistant_greeting': 'प्रणाम! हम अहाँक AI कृषि विशेषज्ञ छी। अहाँक गहुँक फसल 45 दिनक अछि। आइ हम अहाँक कोना मदद कऽ सकैत छी?',
    'user_question': 'खेतक कोना मे पातक रंग पियर भऽ रहल अछि।',
    'assistant_reply': 'पियर पातक अर्थ नाइट्रोजनक कमी वा जलजमाव भऽ सकैत अछि। की हाल मे भारी वर्षा भेल छल? वा अहाँ फोटो पठा सकैत छी?',
    'btn_send_photo': 'फोटो पठाउ',
    'btn_talk_human': 'मानव विशेषज्ञसँ गप करू',
    'input_placeholder': 'टाइप करू वा बाजु...',
    'market_title': 'कृषि बाजार',
    'market_powered': 'रेज़रपे द्वारा संचालित',
    'tab_farmer_sales': 'किसान बिक्री',
    'tab_brand_store': 'ब्रांड स्टोर',
    'zero_commission': '⚡ 0% कमीशन किसान-सँ-किसान बाजार',
    'seller_label': 'विक्रेता:',
    'btn_negotiate': 'मोलभाव करू',
    'scanner_title': 'फसल AI इंजन',
    'scanner_subtitle': 'प्लांटविलेज डेटासेट एकीकरण',
    'scanner_position': 'पौधाकें फ्रेम मे राखू',
    'scanner_desc': 'वास्तविक कैमरा लॉजिकक उपयोग करैत अछि।',
    'scanner_capture': 'तस्वीर खींचू',
    'scanner_btn_scan_another': 'दोसर पौधा स्कैन करू',
    'scanner_smart_rx': 'स्मार्ट पर्ची',
    'scanner_chemical_req': 'दवाक आवश्यकता',
    'scanner_water_mix': 'पानिक मात्रा',
    'scanner_btn_back': 'परिणाम पर वापस जाउ',
    'home_greeting': 'प्रणाम, रमेश 👋',
    'home_location': 'मिथिला, भारत',
    'home_loading': 'स्मार्ट जानकारी लोड भऽ रहल अछि...',
    'home_scan_title': 'पौधा स्कैन करू',
    'home_scan_desc': 'AI द्वारा तुरंत बीमारीक पता लगाउ',
    'home_btn_medicines': 'दवाइयाँ',
    'home_btn_buysell': 'किनू/बेचू',
    'home_btn_expert': 'विशेषज्ञसँ पुछू',
    'home_btn_dashboard': 'डैशबोर्ड',
    'home_health_score': 'फसल स्वास्थ्य स्कोर',
    'home_weather_alerts': 'स्थानीय अलर्ट',
    'nav_home': 'होम',
    'nav_scan': 'स्कैन',
    'nav_shop': 'दुकान',
    'nav_community': 'समाज',
    'nav_profile': 'प्रोफाइल',
    'pd_suite': 'प्लांट डॉक्टर सूट',
    'field_walk': 'हर खेत के चक्कर के लेल।',
    'prof_heading': 'किसान प्रोफाइल',
    'prof_farm_identity': 'खेत पहचान',
    'prof_farm_type_sub': 'खेतक किसिम',
    'prof_farm_size': 'खेतक नाप',
    'prof_voice': 'आवाज सहायक',
    'prof_location': 'लोकेशन अलर्ट',
    'prof_enabled': 'चालू',
    'prof_disabled': 'बंद',
    'prof_allowed': 'अनुमति',
    'prof_skipped': 'छोड़ल',
    'prof_crop_profile': 'फसल प्रोफाइल',
    'prof_selected_crops': 'अहाँक फसल',
    'prof_edit': 'बदलू',
    'prof_app_language': 'ऐप भाषा',
    'prof_notif': 'सूचना',
    'prof_notif_sub': 'रोज अलर्ट, स्कैन रिपोर्ट',
    'prof_privacy': 'गोपनीयता आ सुरक्षा',
    'prof_privacy_sub': 'डेटा अहाँक डिवाइस पर रहत',
    'prof_prefs': 'ऐप सेटिंग',
    'prof_prefs_sub': 'कैमरा, आवाज, थीम',
    'prof_restart': 'ऑनबोर्डिंग फेर शुरू करू',
    'scanner_pipeline_scan': 'Scan',
    'scanner_pipeline_diagnose': 'Diagnose',
    'scanner_pipeline_prevent': 'Prevent',
    'scanner_pipeline_dosage': 'Dosage',
    'scanner_pipeline_precaution': 'Precaution',
    'scanner_app_title': 'Plant Scanner',
    'scanner_analyzing_leaf': 'Analyzing Leaf',
    'scanner_checking_pathogens': 'Checking against 38,000+ pathogens',
    'scanner_step_0': 'Extracting visual features',
    'scanner_step_1': 'Pattern matching diseases',
    'scanner_step_2': 'Geo-locating outbreak data',
    'scanner_ai_processing': 'AI Processing',
    'scanner_high_severity': 'High Severity',
    'scanner_medium_severity': 'Medium Severity',
    'scanner_early_detection': 'Early Detection',
    'scanner_match': 'Match',
    'scanner_based_on_visual': 'Based on visual symptoms & local outbreak data',
    'scanner_ai_action': 'AI Action',
    'scanner_human_review': 'Human Review Recommended',
    'scanner_spray_decision': 'Spray decision lene se pehle expert se confirm karein.',
    'scanner_treatment_plan': 'Treatment Plan',
    'scanner_btn_talk': 'Talk to Agronomist Now',
    'scanner_btn_compute': 'Compute Exact Dosage',
    'scanner_btn_shop': 'Shop Products',
    'scanner_btn_new': 'New Scan',
    'scanner_live_badge': 'Live',
    'scanner_center_leaf': 'Center the affected leaf',
    'scanner_camera_unavailable': 'Camera Unavailable',
    'scanner_try_again': 'Try Again',
    'scanner_upload_gallery': 'Or upload from gallery · Supports JPG, PNG, HEIC'
  },
  'मराठी': {
    'expert_title': 'तज्ञ मदत केंद्र',
    'expert_subtitle': '24/7 AI कृषी तज्ञ मदत',
    'assistant_greeting': 'नमस्कार! मी तुमचा AI कृषी तज्ञ आहे. तुमचे गव्हाचे पीक 45 दिवसांचे आहे. आज मी तुमची कशी मदत करू शकतो?',
    'user_question': 'शेताच्या कोपऱ्यात पाने पिवळी पडत आहेत.',
    'assistant_reply': 'पिवळी पाने नायट्रोजनची कमतरता किंवा पाणी साचल्याचे लक्षण असू शकतात. अलीकडे मुसळधार पाऊस पडला होता का? किंवा तुम्ही फोटो पाठवू शकता का?',
    'btn_send_photo': 'फोटो पाठवा',
    'btn_talk_human': 'मानवी तज्ञाशी बोला',
    'input_placeholder': 'टाइप करा किंवा बोला...',
    'market_title': 'कृषी बाजार',
    'market_powered': 'रेझरपे द्वारा संचालित',
    'tab_farmer_sales': 'शेतकरी विक्री',
    'tab_brand_store': 'ब्रँड स्टोअर',
    'zero_commission': '⚡ 0% कमिशन शेतकरी-ते-शेतकरी बाजार',
    'seller_label': 'विक्रेता:',
    'btn_negotiate': 'वाटाघाटी करा',
    'scanner_title': 'पीक AI इंजिन',
    'scanner_subtitle': 'प्लांटव्हिलेज डेटासेट एकत्रीकरण',
    'scanner_position': 'रोप फ्रेममध्ये ठेवा',
    'scanner_desc': 'वास्तविक कॅमेरा लॉजिक वापरते.',
    'scanner_capture': 'फोटो काढा',
    'scanner_btn_scan_another': 'दुसरे रोप स्कॅन करा',
    'scanner_smart_rx': 'स्मार्ट प्रिस्क्रिप्शन',
    'scanner_chemical_req': 'औषधाची आवश्यकता',
    'scanner_water_mix': 'पाण्याचे प्रमाण',
    'scanner_btn_back': 'निकालावर परत जा',
    'home_greeting': 'नमस्कार, रमेश 👋',
    'home_location': 'महाराष्ट्र, भारत',
    'home_loading': 'स्मार्ट माहिती लोड होत आहे...',
    'home_scan_title': 'रोप स्कॅन करा',
    'home_scan_desc': 'AI द्वारे लगेच आजार ओळखा',
    'home_btn_medicines': 'औषधे',
    'home_btn_buysell': 'खरेदी/विक्री',
    'home_btn_expert': 'तज्ञांना विचारा',
    'home_btn_dashboard': 'डॅशबोर्ड',
    'home_health_score': 'पीक आरोग्य स्कोअर',
    'home_weather_alerts': 'स्थानिक अलर्ट',
    'nav_home': 'होम',
    'nav_scan': 'स्कॅन',
    'nav_shop': 'दुकान',
    'nav_community': 'समाज',
    'nav_profile': 'प्रोफाईल',
    'pd_suite': 'प्लांट डॉक्टर सूट',
    'field_walk': 'प्रत्येक शेत फेरीसाठी।',
    'prof_heading': 'शेतकरी प्रोफाइल',
    'prof_farm_identity': 'शेत ओळख',
    'prof_farm_type_sub': 'शेताचा प्रकार',
    'prof_farm_size': 'शेताचे क्षेत्र',
    'prof_voice': 'व्हॉइस असिस्टंट',
    'prof_location': 'स्थान सूचना',
    'prof_enabled': 'सुरू',
    'prof_disabled': 'बंद',
    'prof_allowed': 'परवानगी',
    'prof_skipped': 'वगळले',
    'prof_crop_profile': 'पीक प्रोफाइल',
    'prof_selected_crops': 'तुमची निवडलेली पिके',
    'prof_edit': 'बदला',
    'prof_app_language': 'ॲप भाषा',
    'prof_notif': 'सूचना',
    'prof_notif_sub': 'दैनंदिन अलर्ट, स्कॅन रिपोर्ट',
    'prof_privacy': 'गोपनीयता व सुरक्षा',
    'prof_privacy_sub': 'डेटा तुमच्या डिव्हाइसवर राहतो',
    'prof_prefs': 'ॲप सेटिंग्ज',
    'prof_prefs_sub': 'कॅमेरा, आवाज, थीम',
    'prof_restart': 'ऑनबोर्डिंग पुन्हा सुरू करा',
    'scanner_pipeline_scan': 'Scan',
    'scanner_pipeline_diagnose': 'Diagnose',
    'scanner_pipeline_prevent': 'Prevent',
    'scanner_pipeline_dosage': 'Dosage',
    'scanner_pipeline_precaution': 'Precaution',
    'scanner_app_title': 'Plant Scanner',
    'scanner_analyzing_leaf': 'Analyzing Leaf',
    'scanner_checking_pathogens': 'Checking against 38,000+ pathogens',
    'scanner_step_0': 'Extracting visual features',
    'scanner_step_1': 'Pattern matching diseases',
    'scanner_step_2': 'Geo-locating outbreak data',
    'scanner_ai_processing': 'AI Processing',
    'scanner_high_severity': 'High Severity',
    'scanner_medium_severity': 'Medium Severity',
    'scanner_early_detection': 'Early Detection',
    'scanner_match': 'Match',
    'scanner_based_on_visual': 'Based on visual symptoms & local outbreak data',
    'scanner_ai_action': 'AI Action',
    'scanner_human_review': 'Human Review Recommended',
    'scanner_spray_decision': 'Spray decision lene se pehle expert se confirm karein.',
    'scanner_treatment_plan': 'Treatment Plan',
    'scanner_btn_talk': 'Talk to Agronomist Now',
    'scanner_btn_compute': 'Compute Exact Dosage',
    'scanner_btn_shop': 'Shop Products',
    'scanner_btn_new': 'New Scan',
    'scanner_live_badge': 'Live',
    'scanner_center_leaf': 'Center the affected leaf',
    'scanner_camera_unavailable': 'Camera Unavailable',
    'scanner_try_again': 'Try Again',
    'scanner_upload_gallery': 'Or upload from gallery · Supports JPG, PNG, HEIC'
  },
  'ગુજરાતી': {
    'expert_title': 'નિષ્ણાત સહાય કેન્દ્ર',
    'expert_subtitle': '24/7 AI અને કૃષિ નિષ્ણાત સહાય',
    'assistant_greeting': 'નમસ્તે! હું તમારો AI કૃષિ નિષ્ણાત છું. તમારો ઘઉંનો પાક 45 દિવસનો છે. આજે હું તમારી કેવી રીતે મદદ કરી શકું?',
    'user_question': 'ખેતરના ખૂણામાં પાંદડા પીળા પડી રહ્યા છે.',
    'assistant_reply': 'પીળા પાંદડા નાઇટ્રોજનની ઉણપ અથવા પાણી ભરાઈ જવાના સંકેત હોઈ શકે છે. શું તાજેતરમાં ભારે વરસાદ થયો હતો? અથવા શું તમે ફોટો મોકલી શકો છો?',
    'btn_send_photo': 'ફોટો મોકલો',
    'btn_talk_human': 'માનવીય નિષ્ણાત સાથે વાત કરો',
    'input_placeholder': 'ટાઇપ કરો અથવા બોલો...',
    'market_title': 'કૃષિ બજાર',
    'market_powered': 'રેઝરપે દ્વારા સંચાલિત',
    'tab_farmer_sales': 'ખેડૂત વેચાણ',
    'tab_brand_store': 'બ્રાન્ડ સ્ટોર',
    'zero_commission': '⚡ 0% કમિશન ખેડૂત-થી-ખેડૂત બજાર',
    'seller_label': 'વેચાણકાર:',
    'btn_negotiate': 'વાટાઘાટો કરો',
    'scanner_title': 'પાક AI એન્જિન',
    'scanner_subtitle': 'પ્લાન્ટવિલેજ ડેટાસેટ એકીકરણ',
    'scanner_position': 'છોડને ફ્રેમમાં રાખો',
    'scanner_desc': 'વાસ્તવિક કેમેરા લોજિકનો ઉપયોગ કરે છે.',
    'scanner_capture': 'ફોટો ખેંચો',
    'scanner_btn_scan_another': 'બીજો છોડ સ્કેન કરો',
    'scanner_smart_rx': 'સ્માર્ટ પ્રિસ્ક્રિપ્શન',
    'scanner_chemical_req': 'દવાની જરૂરિયાત',
    'scanner_water_mix': 'પાણીનું પ્રમાણ',
    'scanner_btn_back': 'પરિણામ પર પાછા જાઓ',
    'home_greeting': 'નમસ્તે, રમેશ 👋',
    'home_location': 'ગુજરાત, ભારત',
    'home_loading': 'સ્માર્ટ માહિતી લોડ થઈ રહી છે...',
    'home_scan_title': 'છોડ સ્કેન કરો',
    'home_scan_desc': 'AI દ્વારા તરત જ રોગ શોધો',
    'home_btn_medicines': 'દવાઓ',
    'home_btn_buysell': 'ખરીદો/વેચો',
    'home_btn_expert': 'નિષ્ણાતને પૂછો',
    'home_btn_dashboard': 'ડેશબોર્ડ',
    'home_health_score': 'પાક આરોગ્ય સ્કોર',
    'home_weather_alerts': 'સ્થાનિક એલર્ટ',
    'nav_home': 'હોમ',
    'nav_scan': 'સ્કૅન',
    'nav_shop': 'દુકાન',
    'nav_community': 'સમાજ',
    'nav_profile': 'પ્રોફાઈલ',
    'pd_suite': 'પ્લાન્ટ ડૉક્ટર સૂટ',
    'field_walk': 'દરેક ખેત ચક્કર માટે।',
    'prof_heading': 'ખેડૂત પ્રોફાઇલ',
    'prof_farm_identity': 'ખેતર ઓળખ',
    'prof_farm_type_sub': 'ખેતરનો પ્રકાર',
    'prof_farm_size': 'ખેતરનું ક્ષેત્ર',
    'prof_voice': 'વૉઇસ આસિસ્ટન્ટ',
    'prof_location': 'સ્થાન ચેતવણી',
    'prof_enabled': 'ચાલુ',
    'prof_disabled': 'બંધ',
    'prof_allowed': 'મંજૂર',
    'prof_skipped': 'છોડ્યું',
    'prof_crop_profile': 'પાક પ્રોફાઇલ',
    'prof_selected_crops': 'તમારા પસંદ કરેલ પાક',
    'prof_edit': 'બદલો',
    'prof_app_language': 'ઐપ ભાષા',
    'prof_notif': 'સૂચનાઓ',
    'prof_notif_sub': 'રોજ અલર્ટ, સ્કૅન રિપોર્ટ',
    'prof_privacy': 'ગોપનીયતા અને સુરક્ષા',
    'prof_privacy_sub': 'ડેટા તમારા ઉપકરણ પર રહે છે',
    'prof_prefs': 'ઐપ સેટિંગ',
    'prof_prefs_sub': 'કૅમેરા, અવાજ, થીમ',
    'prof_restart': 'ઓનબોર્ડિંગ ફરી શરૂ કરો',
    'scanner_pipeline_scan': 'Scan',
    'scanner_pipeline_diagnose': 'Diagnose',
    'scanner_pipeline_prevent': 'Prevent',
    'scanner_pipeline_dosage': 'Dosage',
    'scanner_pipeline_precaution': 'Precaution',
    'scanner_app_title': 'Plant Scanner',
    'scanner_analyzing_leaf': 'Analyzing Leaf',
    'scanner_checking_pathogens': 'Checking against 38,000+ pathogens',
    'scanner_step_0': 'Extracting visual features',
    'scanner_step_1': 'Pattern matching diseases',
    'scanner_step_2': 'Geo-locating outbreak data',
    'scanner_ai_processing': 'AI Processing',
    'scanner_high_severity': 'High Severity',
    'scanner_medium_severity': 'Medium Severity',
    'scanner_early_detection': 'Early Detection',
    'scanner_match': 'Match',
    'scanner_based_on_visual': 'Based on visual symptoms & local outbreak data',
    'scanner_ai_action': 'AI Action',
    'scanner_human_review': 'Human Review Recommended',
    'scanner_spray_decision': 'Spray decision lene se pehle expert se confirm karein.',
    'scanner_treatment_plan': 'Treatment Plan',
    'scanner_btn_talk': 'Talk to Agronomist Now',
    'scanner_btn_compute': 'Compute Exact Dosage',
    'scanner_btn_shop': 'Shop Products',
    'scanner_btn_new': 'New Scan',
    'scanner_live_badge': 'Live',
    'scanner_center_leaf': 'Center the affected leaf',
    'scanner_camera_unavailable': 'Camera Unavailable',
    'scanner_try_again': 'Try Again',
    'scanner_upload_gallery': 'Or upload from gallery · Supports JPG, PNG, HEIC'
  },
  'తెలుగు': {
    'expert_title': 'నిపుణుల మద్దతు కేంద్రం',
    'expert_subtitle': '24/7 AI మరియు వ్యవసాయ నిపుణుల సహాయం',
    'assistant_greeting': 'నమస్కారం! నేను మీ AI వ్యవసాయ నిపుణుడిని. మీ గోధుమ పంట 45 రోజుల వయస్సులో ఉంది. ఈ రోజు నేను మీకు ఎలా సహాయపడగలను?',
    'user_question': 'పొలం మూలలో ఆకులు పసుపు రంగులోకి మారుతున్నాయి.',
    'assistant_reply': 'పసుపు ఆకులు నత్రజని లోపం లేదా నీరు నిలిచిపోవడాన్ని సూచిస్తాయి. ఇటీవల భారీ వర్షం కురిసిందా? లేదా మీరు ఫోటో పంపగలరా?',
    'btn_send_photo': 'ఫోటో పంపండి',
    'btn_talk_human': 'మానవ నిపుణుడితో మాట్లాడండి',
    'input_placeholder': 'టైప్ చేయండి లేదా మాట్లాడండి...',
    'market_title': 'కృషి బజార్',
    'market_powered': 'రేజర్‌పే ద్వారా ఆధారితం',
    'tab_farmer_sales': 'రైతు అమ్మకాలు',
    'tab_brand_store': 'బ్రాండ్ స్టోర్',
    'zero_commission': '⚡ 0% కమీషన్ రైతు నుండి రైతు మార్కెట్',
    'seller_label': 'విక్రేత:',
    'btn_negotiate': 'బేరసారాలు చేయండి',
    'scanner_title': 'పంట AI ఇంజిన్',
    'scanner_subtitle': 'ప్లాంట్‌విలేజ్ డేటాసెట్ ఇంటిగ్రేషన్',
    'scanner_position': 'మొక్కను ఫ్రేమ్‌లో ఉంచండి',
    'scanner_desc': 'వాస్తవ కెమెరా లాజిక్‌ను ఉపయోగిస్తుంది.',
    'scanner_capture': 'ఫోటో తీయండి',
    'scanner_btn_scan_another': 'మరొక మొక్కను స్కాన్ చేయండి',
    'scanner_smart_rx': 'స్మార్ట్ ప్రిస్క్రిప్షన్',
    'scanner_chemical_req': 'మందుల అవసరం',
    'scanner_water_mix': 'నీటి మిశ్రమం',
    'scanner_btn_back': 'ఫలితానికి తిరిగి వెళ్లండి',
    'home_greeting': 'నమస్కారం, రమేష్ 👋',
    'home_location': 'ఆంధ్రప్రదేశ్, భారతదేశం',
    'home_loading': 'స్మార్ట్ సమాచారం లోడ్ అవుతోంది...',
    'home_scan_title': 'మొక్కను స్కాన్ చేయండి',
    'home_scan_desc': 'AI ద్వారా తక్షణమే వ్యాధిని గుర్తించండి',
    'home_btn_medicines': 'మందులు',
    'home_btn_buysell': 'కొనుగోలు/అమ్మకం',
    'home_btn_expert': 'నిపుణుడిని అడగండి',
    'home_btn_dashboard': 'డాష్‌బోర్డ్',
    'home_health_score': 'పంట ఆరోగ్య స్కోర్',
    'home_weather_alerts': 'స్థానిక హెచ్చరికలు',
    'nav_home': 'హోమ్',
    'nav_scan': 'స్కాన్',
    'nav_shop': 'దుకాణం',
    'nav_community': 'సమాజం',
    'nav_profile': 'ప్రొఫైల్',
    'pd_suite': 'ప్లాంట్ డాక్టర్ సూట్',
    'field_walk': 'ప్రతి పొలం పర్యటనకు।',
    'prof_heading': 'రైతు ప్రొఫైల్',
    'prof_farm_identity': 'పొలం గుర్తింపు',
    'prof_farm_type_sub': 'పొలం రకం',
    'prof_farm_size': 'పొలం వైశాల్యం',
    'prof_voice': 'వాయిస్ అసిస్టెంట్',
    'prof_location': 'లొకేషన్ అలర్ట్',
    'prof_enabled': 'ప్రారంభించబడింది',
    'prof_disabled': 'ఆపివేయబడింది',
    'prof_allowed': 'అనుమతి',
    'prof_skipped': 'దాటవేయబడింది',
    'prof_crop_profile': 'పంట ప్రొఫైల్',
    'prof_selected_crops': 'మీరు ఎంచుకున్న పంటలు',
    'prof_edit': 'మార్చు',
    'prof_app_language': 'యాప్ భాష',
    'prof_notif': 'నోటిఫికేషన్లు',
    'prof_notif_sub': 'రోజువారీ అలర్ట్లు, స్కాన్ నివేదిక',
    'prof_privacy': 'గోప్యత మరియు భద్రత',
    'prof_privacy_sub': 'డేటా మీ పరికరంలో ఉంటుంది',
    'prof_prefs': 'యాప్ సెట్టింగులు',
    'prof_prefs_sub': 'కెమెరా, వాయిస్, థీమ్',
    'prof_restart': 'ఓన్‌బోర్డింగ్ మళ్ళీ ప్రారంభించండి'
  }
,
    'scanner_pipeline_scan': 'Scan',
    'scanner_pipeline_diagnose': 'Diagnose',
    'scanner_pipeline_prevent': 'Prevent',
    'scanner_pipeline_dosage': 'Dosage',
    'scanner_pipeline_precaution': 'Precaution',
    'scanner_app_title': 'Plant Scanner',
    'scanner_analyzing_leaf': 'Analyzing Leaf',
    'scanner_checking_pathogens': 'Checking against 38,000+ pathogens',
    'scanner_step_0': 'Extracting visual features',
    'scanner_step_1': 'Pattern matching diseases',
    'scanner_step_2': 'Geo-locating outbreak data',
    'scanner_ai_processing': 'AI Processing',
    'scanner_high_severity': 'High Severity',
    'scanner_medium_severity': 'Medium Severity',
    'scanner_early_detection': 'Early Detection',
    'scanner_match': 'Match',
    'scanner_based_on_visual': 'Based on visual symptoms & local outbreak data',
    'scanner_ai_action': 'AI Action',
    'scanner_human_review': 'Human Review Recommended',
    'scanner_spray_decision': 'Spray decision lene se pehle expert se confirm karein.',
    'scanner_treatment_plan': 'Treatment Plan',
    'scanner_btn_talk': 'Talk to Agronomist Now',
    'scanner_btn_compute': 'Compute Exact Dosage',
    'scanner_btn_shop': 'Shop Products',
    'scanner_btn_new': 'New Scan',
    'scanner_live_badge': 'Live',
    'scanner_center_leaf': 'Center the affected leaf',
    'scanner_camera_unavailable': 'Camera Unavailable',
    'scanner_try_again': 'Try Again',
    'scanner_upload_gallery': 'Or upload from gallery · Supports JPG, PNG, HEIC'};

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);
const STORAGE_KEY = 'plant-doctor/language';

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Always init with 'English' so SSR and first client render are identical (no hydration mismatch)
  const [language, setLanguage] = useState('English');

  // After mount, load the real saved language from localStorage
  useEffect(() => {
    try {
      const savedLanguage = window.localStorage.getItem(STORAGE_KEY);
      if (savedLanguage && dictionary[savedLanguage]) {
        setLanguage(savedLanguage);
      }
    } catch (error) {
      console.error('Failed to restore language', error);
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    try {
      window.localStorage.setItem(STORAGE_KEY, language);
      document.documentElement.lang = getSpeechLangCode(language).split('-')[0];

      // Sync preference to backend (best-effort)
      const userId = window.localStorage.getItem('plant-doctor/user_id') || 'default_user';
      fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:8000'}/api/users/preferences`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ user_id: userId, language })
      }).catch(err => console.debug('Language sync failed:', err));
    } catch (error) {
      console.error('Failed to persist language', error);
    }
  }, [language]);

  const t = (key: string) => {
    return dictionary[language]?.[key] || dictionary['English']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
